### ISSUE TITLE
[Octo-Bot] Bugs found in healthcare-web-bot

### ISSUE THREAD

**Issue by joelczk** [nus-ncl/OctoBot#19]
Test directory in Octo-Bot contains duplicate `testmain.py` files and `uitest.py` is redundant.

**Comment by ariscahyadi** [comment]
Thanks, @joelczk for your comment.

We need these necessary changes:
- delete "testmain.py" and "test.py"
- keep "testMain.py" as test without UI and "uitest.py" as test with UI

But since this is not major issue, we will put in the fix in the next release.

**Comment by ariscahyadi** [comment]
This issue has been addressed here #21

**Comment by ariscahyadi** [comment]
It has been resolved!
