### ISSUE TITLE
[bug] [OctoBot/web-browsing-bot] Running random_web_browsing_crawl_first is never ending 

### ISSUE THREAD

**Issue by yburansac** [nus-ncl/OctoBot#52]
Running web-browsing bot for any website (e.g. docker run web-browsing-bot https://ncl.sg/ 1) with mandatory parameter -c 1 never ends, needs Ctrl + C interrupt. 

![image](https://user-images.githubusercontent.com/42636412/167411005-70ecead9-fb60-44d7-b5a3-94126162834e.png)

**Comment by ariscahyadi** [comment]
Hi @yburansac ... it is intended to make it in a loop (never-ending), so that's why we give another option to limit based on the time and how depth you want to crawl.
```
ncl@android-app-big:~$ docker run nusncl1/web-browsing-bot -h
usage: main.py [-h] [-t T] [-d D] [-s S] [--debug DEBUG] u c

Arguments for program

positional arguments:
  u              Target Website URL
  c              1 for crawl before browsing, 0 (default) otherwise

optional arguments:
  -h, --help     show this help message and exit
  -t T           Time given to crawl website (sec)
  -d D           How deep to crawl website from entrypoint
  -s S           Set to 0 to allow it to crawl to diff. domain
  --debug DEBUG  Set to 1 for debug output
```
