### ISSUE TITLE
[bug] [OctoBot/web-browsing-bot] A non-existent DNS name handling 

### ISSUE THREAD

**Issue by yburansac** [nus-ncl/OctoBot#53]
Running e.g. docker run web-browsing-bot https://www.munni.cz/ 0 where munni.cz is a non-existing domain ends with an error instead of handling exceptions. 
 
![image](https://user-images.githubusercontent.com/42636412/167414275-6724b895-9d8d-4b14-a6ac-fb557a68b024.png)

**Comment by ariscahyadi** [comment]
Thanks, @yburansac .. we will try to fix the exception on this error.

**Comment by ariscahyadi** [comment]
Currently.. we will keep as it is since if the URL failed we ned to know the error.
