### ISSUE TITLE
[bug] [OctoBot/javascript-web-bot] The driver is not executable: /bot/drivers/chromedriver exception

### ISSUE THREAD

**Issue by yburansac** [nus-ncl/OctoBot#54]
Running Dockerfile for javascript-web-bot ends with Java exception - for samples as well as for random websites: 

![image](https://user-images.githubusercontent.com/42636412/167572949-a1079b9b-9652-43b0-aa33-6ac3708e1086.png)

I can successfully run the sample/CTFd, but it ends with the same error. 
![image](https://user-images.githubusercontent.com/42636412/167573353-4cb0c0f8-7c7c-4ee9-b439-2966bf9093db.png)

**Comment by ariscahyadi** [comment]
Hi @yburansac how about running from our bot repository? nusncl1/javascript-web-bot:latest

**Comment by ariscahyadi** [comment]
It happened because the file copied into docker is not executable, it needs to be changed with "x" after copying.

**Comment by ariscahyadi** [comment]
Hi @yburansac ... it has been fixed. Sorry for the delay.
