### ISSUE TITLE
[Octo-Play] checkStatus command does not return status information 

### ISSUE THREAD

**Issue by yburansac** [nus-ncl/OctoBot#55]
I have followed the instructions in Octo-Play to run the program and check the job execution but get the following output instead of the one in the guidelines: 

![image](https://user-images.githubusercontent.com/42636412/167602433-227ccdb6-575f-4c07-88b8-2c7385da19cb.png)

I am running Octobot in testing mode with the kind tool with following setting:

![image](https://user-images.githubusercontent.com/42636412/167602583-3a81ea35-7595-4430-acb6-34c471b442f1.png)

**Comment by ariscahyadi** [comment]
Hi @yburansac ... you didn't get status because the bot is still in a "pending" state. Can you wait till it is active? Because we only show the "active" container.

**Comment by ariscahyadi** [comment]
Hi @yburansac can you confirm this issue? otherwise I will close it.

**Comment by yburansac** [comment]
Sorry for the delay. Yes, I can confirm that for the pending state, there is no output. However, all pods in my kind cluster are currently pending and stuck there. Therefore, I can't check the output for running status yet.
