### ISSUE TITLE
[Octo-Bot/file-transfer-bot] Timeout feature

### ISSUE THREAD

**Issue by slunicko-ondra** [nus-ncl/OctoBot#63]
I've tested file-transfer-bot, and I've missed some timeout. The bot runs forever, so I have to terminate it manually. It would be great to have an argument in which I could specify the timeout (e. g. after 5 minutes, 20 downloads/uploads, or something like this). So the bot would stop automatically.

**Comment by ariscahyadi** [comment]
Hi @slunicko-ondra ... we added the features. Please try it before we can close this ticket.

**Comment by slunicko-ondra** [comment]
Hi @ariscahyadi, I tried it, and it works. Thanks.

**Comment by ariscahyadi** [comment]
Thanks, @slunicko-ondra. I will close this issue.
