### ISSUE TITLE
[Documentation] Tracking for any mistakes in the README for 20.07 release

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/OctoBot#9]
The mistakes can be:
- Typos
- Broken link
- Command & output mismatch
- etc

**Comment by ariscahyadi** [comment]
`Run Octo-Play Program` in the Octo-App README.

**Comment by krusagiz** [comment]
The link for `4. Development Guide for Developer/Researcher` in the root README leads to a non-existent resource `Octo-Bot/README.md`.

**Comment by joelczk** [comment]
Currently, the command `getBotNumbers` and `setBotNumbers` is missing from the `Octo-Play/README.md` documentation

**Comment by ariscahyadi** [comment]
We need to update the licensing and credits/contributors list.

**Comment by ariscahyadi** [comment]
> Currently, the command `getBotNumbers` and `setBotNumbers` is missing from the `Octo-Play/README.md` documentation

`setReplicas` needs to be changed into `setBotNumbers` in the `Octo-Play/README.md`

**Comment by joelczk** [comment]
`help` command is outdated in OctoPlay README.md documentation

**Comment by ariscahyadi** [comment]
Need to update "DOCS" link in [https://github.com/nus-ncl/OctoBot/tree/master/Octo-Bot/healthcare-web-bot](url)

**Comment by ariscahyadi** [comment]
It has been addressed in PR #22
